//
// Generated file, do not edit! Created by opp_msgc 4.4 from applications/mcoa/proxy_enhanced/messages/control_messages/ACK_SetAddressActive.msg.
//

#ifndef _ACK_SETADDRESSACTIVE_M_H_
#define _ACK_SETADDRESSACTIVE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/mcoa/proxy_enhanced/messages/control_messages/ACK_SetAddressActive.msg</tt> by opp_msgc.
 * <pre>
 * packet ACK_SetAddressActive {
 * 	string sourceName;
 * }
 * </pre>
 */
class ACK_SetAddressActive : public ::cPacket
{
  protected:
    opp_string sourceName_var;

  private:
    void copy(const ACK_SetAddressActive& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ACK_SetAddressActive&);

  public:
    ACK_SetAddressActive(const char *name=NULL, int kind=0);
    ACK_SetAddressActive(const ACK_SetAddressActive& other);
    virtual ~ACK_SetAddressActive();
    ACK_SetAddressActive& operator=(const ACK_SetAddressActive& other);
    virtual ACK_SetAddressActive *dup() const {return new ACK_SetAddressActive(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
};

inline void doPacking(cCommBuffer *b, ACK_SetAddressActive& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ACK_SetAddressActive& obj) {obj.parsimUnpack(b);}


#endif // _ACK_SETADDRESSACTIVE_M_H_
