//
// Generated file, do not edit! Created by opp_msgc 4.4 from applications/mcoa/proxy_enhanced/messages/control_messages/SetChannelActive.msg.
//

#ifndef _SETCHANNELACTIVE_M_H_
#define _SETCHANNELACTIVE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/mcoa/proxy_enhanced/messages/control_messages/SetChannelActive.msg</tt> by opp_msgc.
 * <pre>
 * packet SetChannelActive {
 *     int channelNumber;
 *     string homeAddressOfMN;
 *    
 * }
 * </pre>
 */
class SetChannelActive : public ::cPacket
{
  protected:
    int channelNumber_var;
    opp_string homeAddressOfMN_var;

  private:
    void copy(const SetChannelActive& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SetChannelActive&);

  public:
    SetChannelActive(const char *name=NULL, int kind=0);
    SetChannelActive(const SetChannelActive& other);
    virtual ~SetChannelActive();
    SetChannelActive& operator=(const SetChannelActive& other);
    virtual SetChannelActive *dup() const {return new SetChannelActive(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getChannelNumber() const;
    virtual void setChannelNumber(int channelNumber);
    virtual const char * getHomeAddressOfMN() const;
    virtual void setHomeAddressOfMN(const char * homeAddressOfMN);
};

inline void doPacking(cCommBuffer *b, SetChannelActive& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SetChannelActive& obj) {obj.parsimUnpack(b);}


#endif // _SETCHANNELACTIVE_M_H_
