//
// Generated file, do not edit! Created by opp_msgc 4.4 from applications/mcoa/proxy_enhanced/messages/app_messages/VideoMessage.msg.
//

#ifndef _VIDEOMESSAGE_M_H_
#define _VIDEOMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/mcoa/proxy_enhanced/messages/app_messages/VideoMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet VideoMessage {
 *     int sequenceNumber;
 *  }
 * </pre>
 */
class VideoMessage : public ::cPacket
{
  protected:
    int sequenceNumber_var;

  private:
    void copy(const VideoMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const VideoMessage&);

  public:
    VideoMessage(const char *name=NULL, int kind=0);
    VideoMessage(const VideoMessage& other);
    virtual ~VideoMessage();
    VideoMessage& operator=(const VideoMessage& other);
    virtual VideoMessage *dup() const {return new VideoMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
};

inline void doPacking(cCommBuffer *b, VideoMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, VideoMessage& obj) {obj.parsimUnpack(b);}


#endif // _VIDEOMESSAGE_M_H_
